puts "Creating Usernames..."

User.create(name: "TouRine", password: "ilikepizza")
User.create(name: "Kenezz", password: "budslightlover")
User.create(name: "Geh-rigged", password: "codegawd")
User.create(name: "Shri", password: "srieee")
User.create(name: "Chloemoney", password: "chloelovesmonay")
User.create(name: "TaiLr", password: "ttimestwo")

puts "Creating Games..."

Game.create(title: "Super Smash Bros. Melee", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/13639-super-smash-bros-melee-gamecube-front-cover.jpg")
Game.create(title: "The Legend of Zelda: The Wind Waker", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/19375-the-legend-of-zelda-the-wind-waker-gamecube-front-cover.jpg")
Game.create(title: "Soulcalibur 2", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/24198-soulcalibur-ii-gamecube-front-cover.jpg")
Game.create(title: "F-Zero GX", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/24195-f-zero-gx-gamecube-front-cover.jpg")
Game.create(title: "Paper Mario: The Thousand Year Door", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/37912-paper-mario-the-thousand-year-door-gamecube-front-cover.jpg")
Game.create(title: "Viewtiful Joe", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/26261-viewtiful-joe-gamecube-front-cover.jpg")
Game.create(title: "Super Mario Sunshine", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/14217-super-mario-sunshine-gamecube-front-cover.jpg")
Game.create(title: "Super Monkey Ball", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/26293-super-monkey-ball-gamecube-front-cover.jpg")
Game.create(title: "Mario Kart: Double Dash", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/170229-mario-kart-double-dash-gamecube-front-cover.jpg")
Game.create(title: "Luigi's Mansion", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/26855-luigi-s-mansion-gamecube-front-cover.jpg")
Game.create(title: "Super Mario Strikers", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/57320-super-mario-strikers-gamecube-front-cover.jpg")
Game.create(title: "Eternal Darkness: Sanity's Requiem", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/241098-eternal-darkness-sanity-s-requiem-gamecube-front-cover.jpg")
Game.create(title: "Pikmin", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/26468-pikmin-gamecube-front-cover.jpg")
Game.create(title: "Metroid Prime", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/16403-metroid-prime-gamecube-front-cover.jpg")
Game.create(title: "Animal Crossing", platform: "GameCube", rented: false, image: "https://www.mobygames.com/images/covers/l/27496-animal-crossing-gamecube-front-cover.jpg")
Game.create(title: "The Legend Of Zelda: Ocarina Of Time", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/56747-the-legend-of-zelda-ocarina-of-time-nintendo-64-front-cover.jpg")
Game.create(title: "Super Mario 64", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/6126-super-mario-64-nintendo-64-front-cover.jpg")
Game.create(title: "GoldenEye 007", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/6129-goldeneye-007-nintendo-64-front-cover.jpg")
Game.create(title: "The Legend Of Zelda: Majora's Mask", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/54484-the-legend-of-zelda-majora-s-mask-nintendo-64-front-cover.jpg")
Game.create(title: "Super Smash Bros.", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/6458-super-smash-bros-nintendo-64-front-cover.jpg")
Game.create(title: "Mario Kart 64", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/7708-mario-kart-64-nintendo-64-front-cover.jpg")
Game.create(title: "Banjo-Kazooie", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/17730-banjo-kazooie-nintendo-64-front-cover.jpg")
Game.create(title: "Perfect Dark", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/287446-perfect-dark-nintendo-64-front-cover.png")
Game.create(title: "Starfox 64", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/6132-star-fox-64-nintendo-64-front-cover.jpg")
Game.create(title: "Paper Mario", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/9742-paper-mario-nintendo-64-front-cover.jpg")
Game.create(title: "Donkey Kong 64", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/10279-donkey-kong-64-nintendo-64-front-cover.jpg")
Game.create(title: "Mario Party", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/54462-mario-party-nintendo-64-front-cover.png")
Game.create(title: "Diddy Kong Racing", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/537460-diddy-kong-racing-nintendo-64-front-cover.jpg")
Game.create(title: "WWF No Mercy", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/53477-wwf-no-mercy-nintendo-64-front-cover.jpg")
Game.create(title: "Jet Force Gemini", platform: "Nintendo 64", rented: false, image: "https://www.mobygames.com/images/covers/l/451686-jet-force-gemini-nintendo-64-front-cover.jpg")
Game.create(title: "Wii Sports", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/73764-wii-sports-wii-other.jpg")
Game.create(title: "New Super Mario Bros. Wii", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/172541-new-super-mario-bros-wii-wii-front-cover.jpg")
Game.create(title: "Super Smash Bros. Brawl", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/108708-super-smash-bros-brawl-wii-front-cover.jpg")
Game.create(title: "Super Mario Galaxy", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/153990-super-mario-galaxy-wii-front-cover.png")
Game.create(title: "Just Dance 3", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/586482-just-dance-3-wii-front-cover.jpg")
Game.create(title: "Mario Party 8", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/88949-mario-party-8-wii-front-cover.jpg")
Game.create(title: "The Legend of Zelda: Twilight Princess", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/795647-the-legend-of-zelda-twilight-princess-gamecube-front-cover.jpg")
Game.create(title: "Mario & Sonic at the Olympic Games", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/97253-mario-sonic-at-the-olympic-games-wii-front-cover.jpg")
Game.create(title: "Lego Star Wars: The Complete Saga", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/171262-lego-star-wars-the-complete-saga-wii-front-cover.png")
Game.create(title: "Pokemon Battle Revolution", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/102483-pokemon-battle-revolution-wii-front-cover.jpg")
Game.create(title: "Kirby's Epic Yarn", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/201253-kirby-s-epic-yarn-wii-front-cover.jpg")
Game.create(title: "Punch Out!!", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/240463-punch-out-wii-front-cover.jpg")
Game.create(title: "Carnival Games", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/97348-carnival-games-wii-front-cover.jpg")
Game.create(title: "Monster Hunter Tri", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/706641-monster-hunter-tri-wii-front-cover.jpg")
Game.create(title: "WarioWare: Smooth Moves", platform: "Wii", rented: false, image: "https://www.mobygames.com/images/covers/l/81142-warioware-smooth-moves-wii-front-cover.jpg")
Game.create(title: "The Wonderful 101" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/622788-the-wonderful-101-wii-u-front-cover.jpg")
Game.create(title: "Mario Kart 8" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/285423-mario-kart-8-wii-u-front-cover.jpg")
Game.create(title: "Super Smash Bros. for Wii U" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/307145-super-smash-bros-for-wii-u-wii-u-front-cover.jpg")
Game.create(title: "Xenoblade Chronicles X" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/443763-xenoblade-chronicles-x-wii-u-front-cover.jpg")
Game.create(title: "Super Mario 3D World" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/289674-super-mario-3d-world-wii-u-front-cover.jpg")
Game.create(title: "Super Mario Maker" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/356251-super-mario-maker-wii-u-front-cover.jpg")
Game.create(title: "Bayonetta 2" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/623090-bayonetta-2-wii-u-front-cover.jpg")
Game.create(title: "Pikmin 3" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/335858-pikmin-3-wii-u-front-cover.png")
Game.create(title: "Splatoon" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/323617-splatoon-wii-u-front-cover.jpg")
Game.create(title: "Captain Toad: Treasure Tracker" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/296129-captain-toad-treasure-tracker-wii-u-front-cover.jpg")
Game.create(title: "Star Fox Zero" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/661100-star-fox-zero-wii-u-front-cover.jpg")
Game.create(title: "Pushmo World" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/442260-pushmo-world-wii-u-front-cover.jpg")
Game.create(title: "Rayman Legends" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/427007-rayman-legends-wii-u-front-cover.png")
Game.create(title: "Skylanders Swap Force" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/491464-skylanders-swap-force-wii-front-cover.jpg")
Game.create(title: "Shantae and the Pirate's Curse" , platform: "Wii U", rented: false, image: "https://www.mobygames.com/images/covers/l/481494-shantae-and-the-pirate-s-curse-nintendo-3ds-front-cover.jpg")
Game.create(title: "The Legend of Zelda: Breath of the Wild" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/541221-the-legend-of-zelda-breath-of-the-wild-nintendo-switch-front-cover.jpg")
Game.create(title: "Super Mario Odyssey" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/739464-super-mario-odyssey-nintendo-switch-front-cover.jpg")
Game.create(title: "Celeste" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/463342-celeste-nintendo-switch-front-cover.jpg")
Game.create(title: "Tetris Effect: Connected" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/770503-tetris-effect-nintendo-switch-front-cover.jpg")
Game.create(title: "Xenoblade Chronicles 3" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/826467-xenoblade-chronicles-3-nintendo-switch-front-cover.jpg")
Game.create(title: "Monster Hunter Rise" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/721774-monster-hunter-rise-nintendo-switch-front-cover.jpg")
Game.create(title: "Super Smash Bros. Ultimate" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/525828-super-smash-bros-ultimate-nintendo-switch-front-cover.png")
Game.create(title: "Kirby and the Forgotten Land" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/806110-kirby-and-the-forgotten-land-nintendo-switch-front-cover.jpg")
Game.create(title: "The Great Ace Attorney Chronicles" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/763893-the-great-ace-attorney-chronicles-nintendo-switch-front-cover.jpg")
Game.create(title: "Fire Emblem: Three Houses" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/631229-fire-emblem-three-houses-nintendo-switch-front-cover.jpg")
Game.create(title: "Sonic Mania Plus" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/495329-sonic-mania-plus-nintendo-switch-front-cover.jpg")
Game.create(title: "Astral Chain" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/587844-astral-chain-nintendo-switch-front-cover.jpg")
Game.create(title: "Animal Crossing: New Horizons" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/643192-animal-crossing-new-horizons-nintendo-switch-front-cover.jpg")
Game.create(title: "Super Mario Maker 2" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/733270-super-mario-maker-2-nintendo-switch-front-cover.png")
Game.create(title: "Donkey Kong Country: Tropical Freeze" , platform: "Switch", rented: false, image: "https://www.mobygames.com/images/covers/l/478761-donkey-kong-country-tropical-freeze-nintendo-switch-front-cover.jpg")
Game.create(title: "PaRappa the Rapper" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/6110-parappa-the-rapper-playstation-front-cover.jpg")
Game.create(title: "Silent Hill" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/5929-silent-hill-playstation-front-cover.jpg")
Game.create(title: "Metal Gear Solid" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/33395-metal-gear-solid-playstation-front-cover.jpg")
Game.create(title: "Crash Bandicoot: Warped" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/168695-crash-bandicoot-warped-playstation-front-cover.png")
Game.create(title: "WipEout XL" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/175218-wipeout-xl-playstation-front-cover.png")
Game.create(title: "Oddworld: Abe's Oddysee" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/35062-oddworld-abe-s-oddysee-playstation-front-cover.jpg")
Game.create(title: "Tomb Raider" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/16220-tomb-raider-playstation-front-cover.jpg")
Game.create(title: "Spyro the Dragon" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/103597-spyro-the-dragon-playstation-front-cover.jpg")
Game.create(title: "Time Crisis" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/236036-time-crisis-playstation-front-cover.jpg")
Game.create(title: "Twisted Metal 2: World Tour" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/14294-twisted-metal-2-playstation-front-cover.jpg")
Game.create(title: "Tekken 3" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/162280-tekken-3-playstation-front-cover.jpg")
Game.create(title: "Gran Turismo" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/32681-gran-turismo-playstation-front-cover.jpg")
Game.create(title: "Medal of Honor" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/15522-medal-of-honor-playstation-front-cover.jpg")
Game.create(title: "Dance Dance Revolution" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/8323-dance-dance-revolution-playstation-front-cover.jpg")
Game.create(title: "Crash Team Racing" , platform: "Playstation", rented: false, image: "https://www.mobygames.com/images/covers/l/22041-ctr-crash-team-racing-playstation-front-cover.jpg")
Game.create(title: "Grand Theft Auto III" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/12892-grand-theft-auto-iii-playstation-2-front-cover.jpg")
Game.create(title: "Metal Gear Solid 2: Sons of Liberty" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/16076-metal-gear-solid-2-sons-of-liberty-playstation-2-front-cover.jpg")
Game.create(title: "God of War" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/198187-god-of-war-playstation-2-front-cover.png")
Game.create(title: "Burnout 3: Takedown" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/36743-burnout-3-takedown-playstation-2-front-cover.jpg")
Game.create(title: "God of War II" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/84332-god-of-war-ii-playstation-2-front-cover.png")
Game.create(title: "SSX Tricky" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/17420-ssx-tricky-playstation-2-front-cover.jpg")
Game.create(title: "Okami" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/70288-okami-playstation-2-front-cover.jpg")
Game.create(title: "Twisted Metal: Black" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/16177-twisted-metal-black-playstation-2-front-cover.jpg")
Game.create(title: "Devil May Cry" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/15321-devil-may-cry-playstation-2-front-cover.jpg")
Game.create(title: "Metal Gear Solid 3: Subsistence" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/60225-metal-gear-solid-3-subsistence-playstation-2-front-cover.jpg")
Game.create(title: "Tony Hawk's Underground" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/26552-tony-hawk-s-underground-playstation-2-front-cover.jpg")
Game.create(title: "Ratchet & Clank: Going Commando" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/39678-ratchet-clank-going-commando-playstation-2-front-cover.jpg")
Game.create(title: "NBA Street Vol. 2" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/20831-nba-street-vol-2-playstation-2-front-cover.jpg")
Game.create(title: "Burnout Revenge" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/70453-burnout-revenge-playstation-2-front-cover.jpg")
Game.create(title: "TimeSplitters 2" , platform: "Playstation 2", rented: false, image: "https://www.mobygames.com/images/covers/l/17088-timesplitters-2-playstation-2-front-cover.jpg")
Game.create(title: "LittleBigPlanet" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/131471-littlebigplanet-playstation-3-front-cover.jpg")
Game.create(title: "Uncharted 2: Among Thieves" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/637820-uncharted-2-among-thieves-playstation-3-front-cover.jpg")
Game.create(title: "Metal Gear Solid 4: Guns of the Patriots" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/115412-metal-gear-solid-4-guns-of-the-patriots-playstation-3-front-cover.jpg")
Game.create(title: "Puppeteer" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/459490-puppeteer-playstation-3-front-cover.jpg")
Game.create(title: "God of War III" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/179583-god-of-war-iii-playstation-3-front-cover.jpg")
Game.create(title: "Journey" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/308198-journey-playstation-3-front-cover.jpg")
Game.create(title: "LittleBigPlanet 2" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/518286-littlebigplanet-2-playstation-3-front-cover.jpg")
Game.create(title: "inFAMOUS" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/155841-infamous-playstation-3-front-cover.jpg")
Game.create(title: "Tales of Xillia" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/380212-tales-of-xillia-playstation-3-front-cover.png")
Game.create(title: "Demon's Souls" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/670843-demon-s-souls-playstation-3-front-cover.jpg")
Game.create(title: "Ratchet & Clank Future: Tools of Destruction" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/106710-ratchet-clank-future-tools-of-destruction-playstation-3-front-cover.jpg")
Game.create(title: "Ninja Gaiden Sigma" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/131211-ninja-gaiden-sigma-playstation-3-front-cover.jpg")
Game.create(title: "Fight Night Round 4" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/193740-fight-night-round-4-playstation-3-front-cover.jpg")
Game.create(title: "BlazBlue: Calamity Trigger" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/474800-blazblue-calamity-trigger-playstation-3-front-cover.jpg")
Game.create(title: "Hotline Miami" , platform: "Playstation 3", rented: false, image: "https://www.mobygames.com/images/covers/l/266463-hotline-miami-playstation-3-front-cover.jpg")
Game.create(title: "Last of Us Part 2" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/761679-the-last-of-us-part-ii-playstation-4-front-cover.jpg")
Game.create(title: "Horizon Zero Dawn" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/471025-horizon-zero-dawn-playstation-4-front-cover.jpg")
Game.create(title: "Marvel's Spider-Man" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/521130-marvel-spider-man-playstation-4-front-cover.jpg")
Game.create(title: "Bloodborne" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/499759-bloodborne-playstation-4-front-cover.jpg")
Game.create(title: "Uncharted 4: A Thief's End" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/493648-uncharted-4-a-thief-s-end-playstation-4-front-cover.jpg")
Game.create(title: "The Last Guardian" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/372670-the-last-guardian-playstation-4-front-cover.jpg")
Game.create(title: "Persona 5" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/393195-persona-5-playstation-4-front-cover.jpg")
Game.create(title: "Detroit: Become Human" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/465449-detroit-become-human-playstation-4-front-cover.png")
Game.create(title: "Ghost of Tsushima" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/666918-ghost-of-tsushima-playstation-4-front-cover.png")
Game.create(title: "Tearaway Unfolded" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/476225-tearaway-unfolded-playstation-4-front-cover.jpg")
Game.create(title: "inFAMOUS: Second Son" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/684397-infamous-second-son-playstation-4-front-cover.jpg")
Game.create(title: "Yakuza 6: The Song of Life" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/550739-yakuza-6-the-song-of-life-playstation-4-front-cover.jpg")
Game.create(title: "Concrete Genie" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/595675-concrete-genie-playstation-4-front-cover.png")
Game.create(title: "Ratchet & Clank" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/375618-ratchet-clank-playstation-4-front-cover.jpg")
Game.create(title: "Gran Turismo: Sport" , platform: "Playstation 4", rented: false, image: "https://www.mobygames.com/images/covers/l/375618-ratchet-clank-playstation-4-front-cover.jpg")
Game.create(title: "Astro's Playroom" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/704162-playstation-5-included-game-playstation-5-front-cover.png")
Game.create(title: "Horizon Forbidden West" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/791314-horizon-ii-forbidden-west-playstation-4-front-cover.jpg")
Game.create(title: "Deathloop" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/764574-deathloop-playstation-5-front-cover.jpg")
Game.create(title: "Returnal" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/735671-returnal-playstation-5-front-cover.jpg")
Game.create(title: "Ratchet & Clank: Rift Apart" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/780049-ratchet-clank-rift-apart-playstation-5-front-cover.jpg")
Game.create(title: "Marvel's Spider-Man: Miles Morales" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/696294-marvel-spider-man-miles-morales-playstation-4-front-cover.jpg")
Game.create(title: "Death Stranding Director's Cut" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/843254-death-stranding-director-s-cut-playstation-5-front-cover.jpg")
Game.create(title: "Sackboy: A Big Adventure" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/696331-sackboy-a-big-adventure-playstation-4-front-cover.jpg")
Game.create(title: "Stray" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/837618-stray-playstation-5-front-cover.jpg")
Game.create(title: "Ghostwire: Tokyo" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/804750-ghostwire-tokyo-playstation-5-front-cover.jpg")
Game.create(title: "Gran Turismo 7" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/796191-gran-turismo-7-playstation-4-front-cover.jpg")
Game.create(title: "Destruction AllStars" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/715397-destruction-allstars-playstation-5-front-cover.png")
Game.create(title: "Final Fantasy VII Remake0 Intergrade" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/746007-final-fantasy-vii-remake-intergrade-playstation-5-front-cover.jpg")
Game.create(title: "God of War: Ragnarok" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/847776-god-of-war-ragnarok-playstation-4-front-cover.jpg")
Game.create(title: "Nioh Collection" , platform: "Playstation 5", rented: false, image: "https://www.mobygames.com/images/covers/l/765567-nioh-collection-playstation-4-front-cover.png")
Game.create(title: "Halo: Combat Evolved", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/9494-halo-combat-evolved-xbox-front-cover.jpg")
Game.create(title: "Grand Theft Auto Double Pack", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/26598-rockstar-games-double-pack-grand-theft-auto-xbox-front-cover.jpg")
Game.create(title: "Halo 2", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/38333-halo-2-xbox-front-cover.jpg")
Game.create(title: "Tom Clancy's Splinter Cell: Chaos Theory", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/85259-tom-clancy-s-splinter-cell-chaos-theory-xbox-front-cover.jpg")
Game.create(title: "Star Wars: Knights of the Old Republic", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/25515-star-wars-knights-of-the-old-republic-xbox-front-cover.jpg")
Game.create(title: "Ninja Gaiden", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/99773-ninja-gaiden-xbox-front-cover.jpg")
Game.create(title: "The Chronicles of Riddick: Escape from Butcher Bay", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/39672-the-chronicles-of-riddick-escape-from-butcher-bay-windows-front-cover.jpg")
Game.create(title: "Fable", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/36780-fable-xbox-front-cover.jpg")
Game.create(title: "Tom Clancy's Rainbow Six 3", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/218570-tom-clancy-s-rainbow-six-3-xbox-front-cover.png")
Game.create(title: "JSRF: Jet Set Radio Future", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/15136-jsrf-jet-set-radio-future-xbox-front-cover.jpg")
Game.create(title: "Crimson Skies: High Road to Revenge", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/26465-crimson-skies-high-road-to-revenge-xbox-front-cover.jpg")
Game.create(title: "Jade Empire", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/60863-jade-empire-xbox-front-cover.jpg")
Game.create(title: "Project Gotham Racing 2", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/38083-project-gotham-racing-2-xbox-front-cover.jpg")
Game.create(title: "MechAssault", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/38621-mechassault-xbox-front-cover.jpg")
Game.create(title: "The Elder Scrolls III: Morrowind", platform: "Xbox", rented: false, image: "https://www.mobygames.com/images/covers/l/19326-the-elder-scrolls-iii-morrowind-xbox-front-cover.jpg")
Game.create(title: "Grand Theft Auto IV", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/110820-grand-theft-auto-iv-xbox-360-front-cover.jpg")
Game.create(title: "Fallout 3", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/128449-fallout-3-xbox-360-front-cover.png")
Game.create(title: "BioShock", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/92631-bioshock-xbox-360-front-cover.jpg")
Game.create(title: "The Orange Box", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/95717-the-orange-box-xbox-360-front-cover.jpg")
Game.create(title: "Mass Effect 2", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/306146-mass-effect-2-xbox-360-front-cover.jpg")
Game.create(title: "The Elder Scrolls V: Skyrim", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/232070-the-elder-scrolls-v-skyrim-xbox-360-front-cover.jpg")
Game.create(title: "Red Dead Redemption", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/187138-red-dead-redemption-xbox-360-front-cover.jpg")
Game.create(title: "Portal 2", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/217420-portal-2-xbox-360-front-cover.jpg")
Game.create(title: "Batman: Arkham City", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/246513-batman-arkham-city-xbox-360-front-cover.jpg")
Game.create(title: "Gears of War", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/190259-gears-of-war-xbox-360-front-cover.png")
Game.create(title: "The Elder Scrolls IV: Oblivion", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/77303-the-elder-scrolls-iv-oblivion-xbox-360-front-cover.png")
Game.create(title: "Call of Duty 4: Modern Warfare", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/99411-call-of-duty-4-modern-warfare-xbox-360-front-cover.jpg")
Game.create(title: "Halo 3", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/94755-halo-3-xbox-360-front-cover.jpg")
Game.create(title: "Call of Duty: Modern Warfare 2", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/171064-call-of-duty-modern-warfare-2-xbox-360-front-cover.jpg")
Game.create(title: "Pac-Man Championship Edition DX", platform: "Xbox 360", rented: false, image: "https://www.mobygames.com/images/covers/l/207709-pac-man-championship-edition-dx-xbox-360-front-cover.jpg")
Game.create(title: "Red Dead Redemption 2", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/524742-red-dead-redemption-ii-xbox-one-front-cover.jpg")
Game.create(title: "Grand Theft Auto V", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/506098-grand-theft-auto-v-xbox-one-front-cover.jpg")
Game.create(title: "Metal Gear Solid V: The Phantom Pain", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/506098-grand-theft-auto-v-xbox-one-front-cover.jpg")
Game.create(title: "Resident Evil 2", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/535378-resident-evil-2-xbox-one-front-cover.jpg")
Game.create(title: "INSIDE", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/349713-inside-xbox-one-front-cover.png")
Game.create(title: "Forza Horizon 4", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/518449-forza-horizon-4-windows-apps-front-cover.png")
Game.create(title: "Divinty: Original Sin II - Definitive Edition", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/503948-divinity-original-sin-ii-definitive-edition-xbox-one-front-cover.jpg")
Game.create(title: "What Remains of Edith Finch", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/428884-what-remains-of-edith-finch-xbox-one-front-cover.png")
Game.create(title: "Cuphead: The Delicious Last Course", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/826283-cuphead-the-delicious-last-course-windows-apps-front-cover.jpg")
Game.create(title: "Dragon Quest XI S: Echoes of an Elusive Age - Definitive Edition", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/702859-dragon-quest-xi-s-echoes-of-an-elusive-age-definitive-edition-windows-apps-front-cover.jpg")
Game.create(title: "The Witcher 3: Wild Hunt", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/305109-the-witcher-3-wild-hunt-xbox-one-front-cover.png")
Game.create(title: "Gears 5", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/589166-gears-5-windows-apps-front-cover.jpg")
Game.create(title: "Sekiro: Shadows Die Twice", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/547410-sekiro-shadows-die-twice-xbox-one-front-cover.jpg")
Game.create(title: "Forza Horizon 3", platform: "Xbox One", rented: false, image: "https://www.mobygames.com/images/covers/l/447722-forza-horizon-3-xbox-one-front-cover.jpg")
Game.create(title: "Elden Ring", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/775869-elden-ring-xbox-one-front-cover.jpg")
Game.create(title: "Persona 5 Royal", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/844067-persona-5-royal-nintendo-switch-front-cover.jpg")
Game.create(title: "Hades", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/757246-hades-windows-apps-front-cover.jpg")
Game.create(title: "The Stanley Parable: Ultra Deluxe", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/808708-the-stanley-parable-ultra-deluxe-xbox-one-front-cover.png")
Game.create(title: "Forza Horizon 5", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/775616-forza-horizon-5-windows-apps-front-cover.jpg")
Game.create(title: "Rogue Legacy 2", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/678939-rogue-legacy-2-windows-front-cover.jpg")
Game.create(title: "F1 2021", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/752211-f1-2021-xbox-one-front-cover.jpg")
Game.create(title: "Deathloop", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/838256-deathloop-windows-apps-front-cover.jpg")
Game.create(title: "It Takes Two", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/726220-it-takes-two-xbox-one-front-cover.jpg")
Game.create(title: "Tony Hawk Pro Skater 1 + 2", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/682072-tony-hawk-s-pro-skater-1-2-xbox-one-front-cover.jpg")
Game.create(title: "Immortality", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/833349-immortality-windows-apps-front-cover.jpg")
Game.create(title: "Halo Infinite", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/782138-halo-infinite-campaign-windows-apps-front-cover.png")
Game.create(title: "Hitman 3", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/722011-hitman-iii-xbox-one-front-cover.jpg")
Game.create(title: "Pyschonauts 2", platform: "Xbox Series X", rented: false, image: "https://www.mobygames.com/images/covers/l/759666-psychonauts-2-windows-apps-front-cover.jpg")
Game.create(title: "Disco Elysium: The Final Cut", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/753971-disco-elysium-the-final-cut-macintosh-front-cover.jpg")
Game.create(title: "Half-Life 2", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/38738-half-life-2-windows-front-cover.jpg")
Game.create(title: "Sid Meier's Civilization II", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/1-sid-meier-s-civilization-ii-windows-3-x-front-cover.jpg")
Game.create(title: "Half-Life", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/74770-half-life-windows-front-cover.jpg")
Game.create(title: "Quake", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/758516-quake-windows-front-cover.jpg")
Game.create(title: "Diablo II", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/34367-diablo-ii-macintosh-front-cover.jpg")
Game.create(title: "Starcraft II: Wings of Liberty", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/695880-starcraft-ii-wings-of-liberty-macintosh-front-cover.jpg")
Game.create(title: "World of Warcraft: Wrath of the Lich King", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/129939-world-of-warcraft-wrath-of-the-lich-king-macintosh-front-cover.jpg")
Game.create(title: "The Sims 3", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/153852-the-sims-3-macintosh-front-cover.jpg")
Game.create(title: "Overwatch", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/339807-overwatch-windows-front-cover.jpg")
Game.create(title: "Microsoft Flight Simulator", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/678795-microsoft-flight-simulator-windows-front-cover.jpg")
Game.create(title: "Counter-Strike: Global Offensive", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/274120-counter-strike-global-offensive-macintosh-front-cover.jpg")
Game.create(title: "Starcraft: Brood War", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/13738-starcraft-brood-war-macintosh-front-cover.jpg")
Game.create(title: "RollerCoaster Tycoon", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/362-rollercoaster-tycoon-windows-front-cover.jpg")
Game.create(title: "The Simpsons: Hit & Run", platform: "PC", rented: false, image: "https://www.mobygames.com/images/covers/l/38693-the-simpsons-hit-run-windows-front-cover.jpg")
Game.create(title: "Super Mario World", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/79892-super-mario-world-snes-front-cover.jpg")
Game.create(title: "Donkey Kong Country", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/25304-donkey-kong-country-snes-front-cover.jpg")
Game.create(title: "Super Metroid", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/16501-super-metroid-snes-front-cover.jpg")
Game.create(title: "Street Fighter II Turbo", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/22876-street-fighter-ii-turbo-snes-front-cover.jpg")
Game.create(title: "Super Castlevania IV", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/33288-super-castlevania-iv-snes-front-cover.jpg")
Game.create(title: "Mega Man X", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/35566-mega-man-x-snes-front-cover.jpg")
Game.create(title: "The Legend of Zelda: A Link to the Past", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/13521-the-legend-of-zelda-a-link-to-the-past-snes-front-cover.jpg")
Game.create(title: "Contra III: The Alien Wars", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/70112-contra-iii-the-alien-wars-snes-front-cover.jpg")
Game.create(title: "Chrono Trigger", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/19744-chrono-trigger-snes-front-cover.jpg")
Game.create(title: "Earthbound", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/336861-earthbound-snes-front-cover.jpg")
Game.create(title: "Secret of Mana", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/30332-secret-of-mana-snes-front-cover.jpg")
Game.create(title: "F-Zero", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/41005-f-zero-snes-front-cover.png")
Game.create(title: "Kirby Super Star", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/262642-kirby-super-star-snes-front-cover.jpg")
Game.create(title: "Star Fox", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/34490-star-fox-snes-front-cover.jpg")
Game.create(title: "NBA Jam: Tournament Edition", platform: "SNES", rented: false, image: "https://www.mobygames.com/images/covers/l/55765-nba-jam-tournament-edition-snes-front-cover.jpg")

puts "Creating Rentals..."

20.times do |i|
    Rental.create(user_id: rand(1..6), game_id: rand(1..238))
end

# Rental.create(user_id: 2, game_id: 1)

puts "Seeding done"