# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts "Creating Usernames..."

User.create(name: "TouRine", password: "ilikepizza")
User.create(name: "Kenezz", password: "budslightlover")
User.create(name: "Geh-rigged", password: "codegawd")
User.create(name: "Vigi", password: "qawsedrf")
User.create(name: "Chloemoney", password: "chloelovesmonay")

puts "Creating Games..."

Game.create(title: "Super Smash Bros. Melee", platform: "GameCube", rented: false)
Game.create(title: "The Legend of Zelda: The Wind Waker", platform: "GameCube", rented: false)
Game.create(title: "Soulcalibur 2", platform: "GameCube", rented: false)
Game.create(title: "F-Zero GX", platform: "GameCube", rented: false)
Game.create(title: "Paper Mario: The Thousand Year Door", platform: "GameCube", rented: false)
Game.create(title: "Viewtiful Joe", platform: "GameCube", rented: false)
Game.create(title: "Super Mario Sunshine", platform: "GameCube", rented: false)
Game.create(title: "Super Moneky Ball", platform: "GameCube", rented: false)
Game.create(title: "Mario Kart: Double Dash", platform: "GameCube", rented: false)
Game.create(title: "Luigi's Mansion", platform: "GameCube", rented: false)
Game.create(title: "Super Mario Strikers", platform: "GameCube", rented: false)
Game.create(title: "Eternal Darkness: Sanity's Requiem", platform: "GameCube", rented: false)
Game.create(title: "Pikmin", platform: "GameCube", rented: false)
Game.create(title: "Metroid Prime", platform: "GameCube", rented: false)
Game.create(title: "Animal Crossing", platform: "GameCube", rented: false)
Game.create(title: "The Legend Of Zelda: Ocarina Of Time", platform: "Nintendo 64", rented: false)
Game.create(title: "Super Mario 64", platform: "Nintendo 64", rented: false)
Game.create(title: "GoldenEye 007", platform: "Nintendo 64", rented: false)
Game.create(title: "The Legend Of Zelda: Majora's Mask", platform: "Nintendo 64", rented: false)
Game.create(title: "Super Smash Bros.", platform: "Nintendo 64", rented: false)
Game.create(title: "Mario Kart 64", platform: "Nintendo 64", rented: false)
Game.create(title: "Banjo-Kazooie", platform: "Nintendo 64", rented: false)
Game.create(title: "Perfect Dark", platform: "Nintendo 64", rented: false)
Game.create(title: "Starfox64", platform: "Nintendo 64", rented: false)
Game.create(title: "Paper Mario", platform: "Nintendo 64", rented: false)
Game.create(title: "Donkey Kong 64", platform: "Nintendo 64", rented: false)
Game.create(title: "Mario Party", platform: "Nintendo 64", rented: false)
Game.create(title: "Diddy Kong Racing", platform: "Nintendo 64", rented: false)
Game.create(title: "WWF No Mercy", platform: "Nintendo 64", rented: false)
Game.create(title: "Jet Force Gemini", platform: "Nintendo 64", rented: false)
Game.create(title: "Wii Sports", platform: "Wii", rented: false)
Game.create(title: "New Super Mario Bros. Wii", platform: "Wii", rented: false)
Game.create(title: "Super Smash Bros. Brawl", platform: "Wii", rented: false)
Game.create(title: "Super Mario Galaxy", platform: "Wii", rented: false)
Game.create(title: "Just Dance 3", platform: "Wii", rented: false)
Game.create(title: "Mario Party 8", platform: "Wii", rented: false)
Game.create(title: "The Legend of Zelda: Twilight Princess", platform: "Wii", rented: false)
Game.create(title: "Mario & Sonic at the Olympic Games", platform: "Wii", rented: false)
Game.create(title: "Lego Star Wars: The Complete Saga", platform: "Wii", rented: false)
Game.create(title: "Pokemon Battle Revolution", platform: "Wii", rented: false)
Game.create(title: "Kirby's Epic Yarn", platform: "Wii", rented: false)
Game.create(title: "Punch Out!!", platform: "Wii", rented: false)
Game.create(title: "Carnivals", platform: "Wii", rented: false)
Game.create(title: "Monster Hunter Tri", platform: "Wii", rented: false)
Game.create(title: "WarioWare: Smooth Moves", platform: "Wii", rented: false)
Game.create(title: "Legend of Zelda: Breath of the Wild" , platform: "Wii U", rented: false)
Game.create(title: "Mario Kart 8" , platform: "Wii U", rented: false)
Game.create(title: "Super Smash Bros. for Wii U" , platform: "Wii U", rented: false)
Game.create(title: "Xenoblade Chronicles X" , platform: "Wii U", rented: false)
Game.create(title: "Super Mario 3D World" , platform: "Wii U", rented: false)
Game.create(title: "Super Mario Maker" , platform: "Wii U", rented: false)
Game.create(title: "Bayonetta 2" , platform: "Wii U", rented: false)
Game.create(title: "Pikmin 3" , platform: "Wii U", rented: false)
Game.create(title: "Splatoon" , platform: "Wii U", rented: false)
Game.create(title: "Captain Toad: Treasure Tracker" , platform: "Wii U", rented: false)
Game.create(title: "Star Fox Zero" , platform: "Wii U", rented: false)
Game.create(title: "Bayonetta" , platform: "Wii U", rented: false)
Game.create(title: "Rayman Legends" , platform: "Wii U", rented: false)
Game.create(title: "Skylanders Swap Force" , platform: "Wii U", rented: false)
Game.create(title: "Shantae and the Pirate's Curse" , platform: "Wii U", rented: false)
Game.create(title: "The Legend of Zelda: Breath of the Wild" , platform: "Switch", rented: false)
Game.create(title: "Super Mario Odyssey" , platform: "Switch", rented: false)
Game.create(title: "Celeste" , platform: "Switch", rented: false)
Game.create(title: "Tetris Effect: Connected" , platform: "Switch", rented: false)
Game.create(title: "Xenoblade Chronicles 3" , platform: "Switch", rented: false)
Game.create(title: "Monster Hunter Rise" , platform: "Switch", rented: false)
Game.create(title: "Super Smash Bros. Ultimate" , platform: "Switch", rented: false)
Game.create(title: "Kirby and the Forgotten Land" , platform: "Switch", rented: false)
Game.create(title: "The Great Ace Attorney Chronicles" , platform: "Switch", rented: false)
Game.create(title: "Fire Emblem: Three Houses" , platform: "Switch", rented: false)
Game.create(title: "Sonic Mania Plus" , platform: "Switch", rented: false)
Game.create(title: "Astral Chain" , platform: "Switch", rented: false)
Game.create(title: "Animal Crossing: New Horizons" , platform: "Switch", rented: false)
Game.create(title: "Super Mario Maker 2" , platform: "Switch", rented: false)
Game.create(title: "Donkey Kong Country: Tropical Freeze" , platform: "Switch", rented: false)
Game.create(title: "PaRappa the Rapper" , platform: "Playstation", rented: false)
Game.create(title: "Silent Hill" , platform: "Playstation", rented: false)
Game.create(title: "Metal Gear Solid" , platform: "Playstation", rented: false)
Game.create(title: "Crash Bandicoot: Warped" , platform: "Playstation", rented: false)
Game.create(title: "WipEout 2097" , platform: "Playstation", rented: false)
Game.create(title: "Oddworld: Abe's Oddysee" , platform: "Playstation", rented: false)
Game.create(title: "Tomb Raider" , platform: "Playstation", rented: false)
Game.create(title: "Spyro the Dragon" , platform: "Playstation", rented: false)
Game.create(title: "Time Crisis" , platform: "Playstation", rented: false)
Game.create(title: "Twisted Metal 2: World Tour" , platform: "Playstation", rented: false)
Game.create(title: "Tekken 3" , platform: "Playstation", rented: false)
Game.create(title: "Gran Turismo" , platform: "Playstation", rented: false)
Game.create(title: "Medal of Honor" , platform: "Playstation", rented: false)
Game.create(title: "Dance Dance Revolution" , platform: "Playstation", rented: false)
Game.create(title: "Crash Team Racing" , platform: "Playstation", rented: false)
Game.create(title: "Grand Theft Auto III" , platform: "Playstation 2", rented: false)
Game.create(title: "Metal Gear Solid 2: Sons of Liberty" , platform: "Playstation 2", rented: false)
Game.create(title: "God of War" , platform: "Playstation 2", rented: false)
Game.create(title: "Burnout 3: Takedown" , platform: "Playstation 2", rented: false)
Game.create(title: "God of War II" , platform: "Playstation 2", rented: false)
Game.create(title: "SSX Tricky" , platform: "Playstation 2", rented: false)
Game.create(title: "Okami" , platform: "Playstation 2", rented: false)
Game.create(title: "Twisted Metal: Black" , platform: "Playstation 2", rented: false)
Game.create(title: "Devil May Cry" , platform: "Playstation 2", rented: false)
Game.create(title: "Metal Gear Solid 3: Subsistence" , platform: "Playstation 2", rented: false)
Game.create(title: "Tony Hawk's Underground" , platform: "Playstation 2", rented: false)
Game.create(title: "Ratchet & Clank: Going Commando" , platform: "Playstation 2", rented: false)
Game.create(title: "NBA Street Vol. 2" , platform: "Playstation 2", rented: false)
Game.create(title: "Burnout Revenge" , platform: "Playstation 2", rented: false)
Game.create(title: "TimeSplitters 2" , platform: "Playstation 2", rented: false)
Game.create(title: "LittleBigPlanet" , platform: "Playstation 3", rented: false)
Game.create(title: "Uncharted 2: Among Thieves" , platform: "Playstation 3", rented: false)
Game.create(title: "Metal Gear Solid 4: Guns of the Patriots" , platform: "Playstation 3", rented: false)
Game.create(title: "Braid" , platform: "Playstation 3", rented: false)
Game.create(title: "God of War III" , platform: "Playstation 3", rented: false)
Game.create(title: "Journey" , platform: "Playstation 3", rented: false)
Game.create(title: "LittleBigPlanet 2" , platform: "Playstation 3", rented: false)
Game.create(title: "Rayman Legends" , platform: "Playstation 3", rented: false)
Game.create(title: "Okami HD" , platform: "Playstation 3", rented: false)
Game.create(title: "Demon's Souls" , platform: "Playstation 3", rented: false)
Game.create(title: "Ratchet & Clank Future: Tools of Destruction" , platform: "Playstation 3", rented: false)
Game.create(title: "Ninja Gaiden Sigma" , platform: "Playstation 3", rented: false)
Game.create(title: "Fight Night Round 4" , platform: "Playstation 3", rented: false)
Game.create(title: "BlazBlue: Calamity Trigger" , platform: "Playstation 3", rented: false)
Game.create(title: "Hotline Miami" , platform: "Playstation 3", rented: false)
Game.create(title: "Last of Us Part 2" , platform: "Playstation 4", rented: false)
Game.create(title: "Horizon Zero Dawn" , platform: "Playstation 4", rented: false)
Game.create(title: "Marvel's Spider-Man" , platform: "Playstation 4", rented: false)
Game.create(title: "Bloodborne" , platform: "Playstation 4", rented: false)
Game.create(title: "Uncharted 4: A Thief's End" , platform: "Playstation 4", rented: false)
Game.create(title: "The Last Guardian" , platform: "Playstation 4", rented: false)
Game.create(title: "Persona 5" , platform: "Playstation 4", rented: false)
Game.create(title: "Detroit: Become Human" , platform: "Playstation 4", rented: false)
Game.create(title: "Ghost of Tsushima" , platform: "Playstation 4", rented: false)
Game.create(title: "Tearaway Unfolded" , platform: "Playstation 4", rented: false)
Game.create(title: "inFamous: Second Son" , platform: "Playstation 4", rented: false)
Game.create(title: "Yakuza 6" , platform: "Playstation 4", rented: false)
Game.create(title: "Concrete Genie" , platform: "Playstation 4", rented: false)
Game.create(title: "Ratchet & Clank" , platform: "Playstation 4", rented: false)
Game.create(title: "GT Sport" , platform: "Playstation 4", rented: false)
Game.create(title: "Astro's Playroom" , platform: "Playstation 5", rented: false)
Game.create(title: "Horizon Forbidden West" , platform: "Playstation 5", rented: false)
Game.create(title: "Demon's Souls" , platform: "Playstation 5", rented: false)
Game.create(title: "Returnal" , platform: "Playstation 5", rented: false)
Game.create(title: "Ratchet & Clank: Rift Apart" , platform: "Playstation 5", rented: false)
Game.create(title: "Marvel's Spider-Man: Miles Morales" , platform: "Playstation 5", rented: false)
Game.create(title: "Death Stranding Director's Cut" , platform: "Playstation 5", rented: false)
Game.create(title: "Sackboy: A Big Adventure" , platform: "Playstation 5", rented: false)
Game.create(title: "Stray" , platform: "Playstation 5", rented: false)
Game.create(title: "Ghostwire: Tokyo" , platform: "Playstation 5", rented: false)
Game.create(title: "Gran Turismo 7" , platform: "Playstation 5", rented: false)
Game.create(title: "Destruction AllStars" , platform: "Playstation 5", rented: false)
Game.create(title: "Final Fantasy VII Remake" , platform: "Playstation 5", rented: false)
Game.create(title: "Horizon Call of the Mountain" , platform: "Playstation 5", rented: false)
Game.create(title: "Pragmata" , platform: "Playstation 5", rented: false)
Game.create(title: "Halo: Combat Evolved", platform: "Xbox", rented: false)
Game.create(title: "Grand Theft Auto Double Pack", platform: "Xbox", rented: false)
Game.create(title: "Halo 2", platform: "Xbox", rented: false)
Game.create(title: "Tom Clancy's Splinter Cell: Chaos Theory
", platform: "Xbox", rented: false)
Game.create(title: "Star Wars: Knights of the Old Republic", platform: "Xbox", rented: false)
Game.create(title: "Ninja Gaiden", platform: "Xbox", rented: false)
Game.create(title: "The Chronicles of Riddick: Escape from Butcher Bay", platform: "Xbox", rented: false)
Game.create(title: "Fable", platform: "Xbox", rented: false)
Game.create(title: "Tom Clancy's Rainbow Six 3", platform: "Xbox", rented: false)
Game.create(title: "Jet Set Radio Future", platform: "Xbox", rented: false)
Game.create(title: "Crimson Skies: High Road to Revenge", platform: "Xbox", rented: false)
Game.create(title: "Jade Empire", platform: "Xbox", rented: false)
Game.create(title: "Project Gotham Racing 2
", platform: "Xbox", rented: false)
Game.create(title: "MechAssault", platform: "Xbox", rented: false)
Game.create(title: "The Elder Scrolls III: Morrowind", platform: "Xbox", rented: false)
Game.create(title: "Grand Theft Auto IV", platform: "Xbox 360", rented: false)
Game.create(title: "Fallout 3", platform: "Xbox 360", rented: false)
Game.create(title: "BioShock", platform: "Xbox 360", rented: false)
Game.create(title: "The Orange Box", platform: "Xbox 360", rented: false)
Game.create(title: "Mass Effect 2", platform: "Xbox 360", rented: false)
Game.create(title: "The Elder Scrolls V: Skyrim", platform: "Xbox 360", rented: false)
Game.create(title: "Red Dead Redemption", platform: "Xbox 360", rented: false)
Game.create(title: "Portal 2", platform: "Xbox 360", rented: false)
Game.create(title: "Batman: Arkham City", platform: "Xbox 360", rented: false)
Game.create(title: "Gears of War", platform: "Xbox 360", rented: false)
Game.create(title: "The Elder Scrolls IV: Oblivion", platform: "Xbox 360", rented: false)
Game.create(title: "Call of Duty 4: Modern Warfare", platform: "Xbox 360", rented: false)
Game.create(title: "Halo 3", platform: "Xbox 360", rented: false)
Game.create(title: "Call of Duty: Modern Warfare 2", platform: "Xbox 360", rented: false)
Game.create(title: "Pac-Man Championship Edition DX", platform: "Xbox 360", rented: false)
Game.create(title: "Red Dead Redemption 2", platform: "Xbox One", rented: false)
Game.create(title: "Grand Theft Auto V", platform: "Xbox One", rented: false)
Game.create(title: "Metal Gear Solid V: The Phantom Pain", platform: "Xbox One", rented: false)
Game.create(title: "Celeste", platform: "Xbox One", rented: false)
Game.create(title: "Resident Evil 2", platform: "Xbox One", rented: false)
Game.create(title: "INSIDE", platform: "Xbox One", rented: false)
Game.create(title: "Forza Horizon 4", platform: "Xbox One", rented: false)
Game.create(title: "Divinty: Original Sin II", platform: "Xbox One", rented: false)
Game.create(title: "What Remains of Edith Finch", platform: "Xbox One", rented: false)
Game.create(title: "Cuphead in the Delicious Last Course", platform: "Xbox One", rented: false)
Game.create(title: "Dragon Quest XI S: Echoes of an Elusive Age", platform: "Xbox One", rented: false)
Game.create(title: "The Witcher 3: Wild Hunt", platform: "Xbox One", rented: false)
Game.create(title: "Gears 5", platform: "Xbox One", rented: false)
Game.create(title: "Sekiro: Shadows Die Twice", platform: "Xbox One", rented: false)
Game.create(title: "Forza Horizon 3", platform: "Xbox One", rented: false)
Game.create(title: "Elden Ring", platform: "Xbox Series X", rented: false)
Game.create(title: "Persona 5 Royal", platform: "Xbox Series X", rented: false)
Game.create(title: "Hades", platform: "Xbox Series X", rented: false)
Game.create(title: "The Stanley Parable: Ultra Deluxe", platform: "Xbox Series X", rented: false)
Game.create(title: "Forza Horizon 5", platform: "Xbox Series X", rented: false)
Game.create(title: "Rogue Legacy 2", platform: "Xbox Series X", rented: false)
Game.create(title: "F1 2021", platform: "Xbox Series X", rented: false)
Game.create(title: "Deathloop", platform: "Xbox Series X", rented: false)
Game.create(title: "It Takes Two", platform: "Xbox Series X", rented: false)
Game.create(title: "Tony Hawk Pro Skater 1 + 2", platform: "Xbox Series X", rented: false)
Game.create(title: "Tetris Effect: Connected", platform: "Xbox Series X", rented: false)
Game.create(title: "Immortality", platform: "Xbox Series X", rented: false)
Game.create(title: "Halo Infinite", platform: "Xbox Series X", rented: false)
Game.create(title: "Hitman 3", platform: "Xbox Series X", rented: false)
Game.create(title: "Pyschonauts 2", platform: "Xbox Series X", rented: false)
Game.create(title: "Disco Elysium: The Final Cut", platform: "PC", rented: false)
Game.create(title: "Half-Life 2", platform: "PC", rented: false)
Game.create(title: "Sid Meier's Civilization II", platform: "PC", rented: false)
Game.create(title: "Half-Life", platform: "PC", rented: false)
Game.create(title: "Quake", platform: "PC", rented: false)
Game.create(title: "Diablo II", platform: "PC", rented: false)
Game.create(title: "Starcraft II: Wings of Liberty", platform: "PC", rented: false)
Game.create(title: "World of Warcraft: Wrath of the Lich King", platform: "PC", rented: false)
Game.create(title: "The Sims 3", platform: "PC", rented: false)
Game.create(title: "Overwatch", platform: "PC", rented: false)
Game.create(title: "Microsoft Flight Simulator", platform: "PC", rented: false)
Game.create(title: "Counter-Strike: Global Offensive", platform: "PC", rented: false)
Game.create(title: "Starcraft: Brood War", platform: "PC", rented: false)
Game.create(title: "RollerCoaster Tycoon", platform: "PC", rented: false)
Game.create(title: "The Simpsons: Hit & Run", platform: "PC", rented: false)
Game.create(title: "Super Mario World", platform: "SNES", rented: false)
Game.create(title: "Donkey Kong Country", platform: "SNES", rented: false)
Game.create(title: "Super Metroid", platform: "SNES", rented: false)
Game.create(title: "Street Fighter II Turbo", platform: "SNES", rented: false)
Game.create(title: "Super Castlevania IV", platform: "SNES", rented: false)
Game.create(title: "Mega Man X", platform: "SNES", rented: false)
Game.create(title: "The Legend of Zelda: A Link to the Past", platform: "SNES", rented: false)
Game.create(title: "Contra III: The Alien Wars", platform: "SNES", rented: false)
Game.create(title: "Chrono Trigger", platform: "SNES", rented: false)
Game.create(title: "Earthbound", platform: "SNES", rented: false)
Game.create(title: "Secret of Mana", platform: "SNES", rented: false)
Game.create(title: "F-Zero", platform: "SNES", rented: false)
Game.create(title: "Kirby Super Star", platform: "SNES", rented: false)
Game.create(title: "Star Fox", platform: "SNES", rented: false)
Game.create(title: "NBA Jam: Tournament Edition", platform: "SNES", rented: false)

puts "Seeding done"
