# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Game.create(title: "Halo: Combat Evolved", platform: "Xbox", rented: false)
Game.create(title: "Grand Theft Auto Double Pack", platform: "Xbox", rented: false)
Game.create(title: "Halo 2", platform: "Xbox", rented: false)
Game.create(title: "Tom Clancy's Splinter Cell: Chaos Theory
", platform: "Xbox", rented: false)
Game.create(title: "Star Wars: Knights of the Old Republic", platform: "Xbox", rented: false)
Game.create(title: "Ninja Gaiden", platform: "Xbox", rented: false)
Game.create(title: "The Chronicles of Riddick: Escape from Butcher Bay", platform: "Xbox", rented: false)
Game.create(title: "Fable", platform: "Xbox", rented: false)
Game.create(title: "Tom Clancy's Rainbow Six 3", platform: "Xbox", rented: false)
Game.create(title: "Jet Set Radio Future", platform: "Xbox", rented: false)
Game.create(title: "Crimson Skies: High Road to Revenge", platform: "Xbox", rented: false)
Game.create(title: "Jade Empire", platform: "Xbox", rented: false)
Game.create(title: "Project Gotham Racing 2
", platform: "Xbox", rented: false)
Game.create(title: "MechAssault", platform: "Xbox", rented: false)
Game.create(title: "The Elder Scrolls III: Morrowind", platform: "Xbox", rented: false)
Game.create(title: "Grand Theft Auto IV", platform: "Xbox 360", rented: false)
Game.create(title: "Fallout 3", platform: "Xbox 360", rented: false)
Game.create(title: "BioShock", platform: "Xbox 360", rented: false)
Game.create(title: "The Orange Box", platform: "Xbox 360", rented: false)
Game.create(title: "Mass Effect 2", platform: "Xbox 360", rented: false)
Game.create(title: "The Elder Scrolls V: Skyrim", platform: "Xbox 360", rented: false)
Game.create(title: "Red Dead Redemption", platform: "Xbox 360", rented: false)
Game.create(title: "Portal 2", platform: "Xbox 360", rented: false)
Game.create(title: "Batman: Arkham City", platform: "Xbox 360", rented: false)
Game.create(title: "Gears of War", platform: "Xbox 360", rented: false)
Game.create(title: "The Elder Scrolls IV: Oblivion", platform: "Xbox 360", rented: false)
Game.create(title: "Call of Duty 4: Modern Warfare", platform: "Xbox 360", rented: false)
Game.create(title: "Halo 3", platform: "Xbox 360", rented: false)
Game.create(title: "Call of Duty: Modern Warfare 2", platform: "Xbox 360", rented: false)
Game.create(title: "Pac-Man Championship Edition DX", platform: "Xbox 360", rented: false)
Game.create(title: "Red Dead Redemption 2", platform: "Xbox One", rented: false)
Game.create(title: "Grand Theft Auto V", platform: "Xbox One", rented: false)
Game.create(title: "Metal Gear Solid V: The Phantom Pain", platform: "Xbox One", rented: false)
Game.create(title: "Celeste", platform: "Xbox One", rented: false)
Game.create(title: "Resident Evil 2", platform: "Xbox One", rented: false)
Game.create(title: "INSIDE", platform: "Xbox One", rented: false)
Game.create(title: "Forza Horizon 4", platform: "Xbox One", rented: false)
Game.create(title: "Divinty: Original Sin II", platform: "Xbox One", rented: false)
Game.create(title: "What Remains of Edith Finch", platform: "Xbox One", rented: false)
Game.create(title: "Cuphead in the Delicious Last Course", platform: "Xbox One", rented: false)
Game.create(title: "Dragon Quest XI S: Echoes of an Elusive Age", platform: "Xbox One", rented: false)
Game.create(title: "The Witcher 3: Wild Hunt", platform: "Xbox One", rented: false)
Game.create(title: "Gears 5", platform: "Xbox One", rented: false)
Game.create(title: "Sekiro: Shadows Die Twice", platform: "Xbox One", rented: false)
Game.create(title: "Forza Horizon 3", platform: "Xbox One", rented: false)
Game.create(title: "Elden Ring", platform: "Xbox Series X", rented: false)
Game.create(title: "Persona 5 Royal", platform: "Xbox Series X", rented: false)
Game.create(title: "Hades", platform: "Xbox Series X", rented: false)
Game.create(title: "The Stanley Parable: Ultra Deluxe", platform: "Xbox Series X", rented: false)
Game.create(title: "Forza Horizon 5", platform: "Xbox Series X", rented: false)
Game.create(title: "Rogue Legacy 2", platform: "Xbox Series X", rented: false)
Game.create(title: "F1 2021", platform: "Xbox Series X", rented: false)
Game.create(title: "Deathloop", platform: "Xbox Series X", rented: false)
Game.create(title: "It Takes Two", platform: "Xbox Series X", rented: false)
Game.create(title: "Tony Hawk Pro Skater 1 + 2", platform: "Xbox Series X", rented: false)
Game.create(title: "Tetris Effect: Connected", platform: "Xbox Series X", rented: false)
Game.create(title: "Immortality", platform: "Xbox Series X", rented: false)
Game.create(title: "Halo Infinite", platform: "Xbox Series X", rented: false)
Game.create(title: "Hitman 3", platform: "Xbox Series X", rented: false)
Game.create(title: "Pyschonauts 2", platform: "Xbox Series X", rented: false)
Game.create(title: "Disco Elysium: The Final Cut", platform: "PC", rented: false)
Game.create(title: "Half-Life 2", platform: "PC", rented: false)
Game.create(title: "Sid Meier's Civilization II", platform: "PC", rented: false)
Game.create(title: "Half-Life", platform: "PC", rented: false)
Game.create(title: "Quake", platform: "PC", rented: false)
Game.create(title: "Diablo II", platform: "PC", rented: false)
Game.create(title: "Starcraft II: Wings of Liberty", platform: "PC", rented: false)
Game.create(title: "World of Warcraft: Wrath of the Lich King", platform: "PC", rented: false)
Game.create(title: "The Sims 3", platform: "PC", rented: false)
Game.create(title: "Overwatch", platform: "PC", rented: false)
Game.create(title: "Microsoft Flight Simulator", platform: "PC", rented: false)
Game.create(title: "Counter-Strike: Global Offensive", platform: "PC", rented: false)
Game.create(title: "Starcraft: Brood War", platform: "PC", rented: false)
Game.create(title: "RollerCoaster Tycoon", platform: "PC", rented: false)
Game.create(title: "The Simpsons: Hit & Run", platform: "PC", rented: false)
Game.create(title: "Super Mario World", platform: "SNES", rented: false)
Game.create(title: "Donkey Kong Country", platform: "SNES", rented: false)
Game.create(title: "Super Metroid", platform: "SNES", rented: false)
Game.create(title: "Street Fighter II Turbo", platform: "SNES", rented: false)
Game.create(title: "Super Castlevania IV", platform: "SNES", rented: false)
Game.create(title: "Mega Man X", platform: "SNES", rented: false)
Game.create(title: "The Legend of Zelda: A Link to the Past", platform: "SNES", rented: false)
Game.create(title: "Contra III: The Alien Wars", platform: "SNES", rented: false)
Game.create(title: "Chrono Trigger", platform: "SNES", rented: false)
Game.create(title: "Earthbound", platform: "SNES", rented: false)
Game.create(title: "Secret of Mana", platform: "SNES", rented: false)
Game.create(title: "F-Zero", platform: "SNES", rented: false)
Game.create(title: "Kirby Super Star", platform: "SNES", rented: false)
Game.create(title: "Star Fox", platform: "SNES", rented: false)
Game.create(title: "NBA Jam: Tournament Edition", platform: "SNES", rented: false)
